apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- route.yaml
- ../../base
namespace: workspaces-system
namePrefix: workspaces-
replacements:
  - source:
      name: ingress-proxy
      kind: Service
      fieldPath: "metadata.name"
    targets:
      - select:
          kind: Route
          group: route.openshift.io
          version: v1
          name: ingress-proxy
        fieldPaths:
          - "spec.to.name"
